kind: pipeline
name: linux-amd64

platform:
    os: linux
    arch: amd64

steps:
- name: Check Syntax
  image: chanbakjsd/antlr4-go:4.7.2
  commands:
  - ./check_go_format.sh

- name: Build Noplang
  image: chanbakjsd/antlr4-go:4.7.2
  commands:
  - ./build.sh 
